/**
 * Data Loader
 *
 * Loads events and videos from JSON files generated by Notion fetch script
 */

class DataLoader {
  constructor() {
    this.events = null;
    this.videos = null;
  }

  /**
   * Load events data
   */
  async loadEvents() {
    try {
      const response = await fetch('data/events.json');
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      this.events = await response.json();
      return this.events;
    } catch (error) {
      console.error('Error loading events:', error);
      // Return empty data structure if file doesn't exist yet
      return {
        upcoming: [],
        past: [],
        lastUpdated: null
      };
    }
  }

  /**
   * Load videos data
   */
  async loadVideos() {
    try {
      const response = await fetch('data/videos.json');
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      this.videos = await response.json();
      return this.videos;
    } catch (error) {
      console.error('Error loading videos:', error);
      // Return empty data structure if file doesn't exist yet
      return {
        videos: [],
        lastUpdated: null
      };
    }
  }

  /**
   * Render events to the page
   */
  renderEvents(container, events, limit = null) {
    if (!container) return;

    const eventsToShow = limit ? events.slice(0, limit) : events;

    if (eventsToShow.length === 0) {
      container.innerHTML = '<p style="text-align: center; color: var(--text-light);">No events available at this time.</p>';
      return;
    }

    container.innerHTML = eventsToShow.map(event => this.createEventCard(event)).join('');
  }

  /**
   * Render detailed event cards for events page
   */
  renderDetailedEvents(container, events) {
    if (!container) return;

    if (events.length === 0) {
      container.innerHTML = '<p style="text-align: center; color: var(--text-light);">No events available at this time.</p>';
      return;
    }

    container.innerHTML = events.map(event => this.createDetailedEventCard(event)).join('');
  }

  /**
   * Create a simple event card for homepage
   */
  createEventCard(event) {
    return `
      <div class="event-card">
        <div class="event-date">
          <span class="day">${event.day}</span>
          <span class="month">${event.month}</span>
        </div>
        <div class="event-details">
          <h3>${this.escapeHtml(event.title)}</h3>
          <p class="event-meta">${this.escapeHtml(event.location)} • ${this.escapeHtml(event.time)}</p>
          <p>${this.escapeHtml(event.description.substring(0, 150))}${event.description.length > 150 ? '...' : ''}</p>
        </div>
      </div>
    `;
  }

  /**
   * Create a detailed event card for events page
   */
  createDetailedEventCard(event) {
    const highlightsHtml = event.highlights && event.highlights.length > 0
      ? `
        <div class="event-highlights">
          <h4>What You'll Learn:</h4>
          <ul>
            ${event.highlights.map(h => `<li>${this.escapeHtml(h)}</li>`).join('')}
          </ul>
        </div>
      `
      : '';

    const registerButton = event.registrationLink
      ? `<a href="${this.escapeHtml(event.registrationLink)}" class="btn btn-primary" target="_blank" rel="noopener">Register Now</a>`
      : '';

    return `
      <div class="event-card-detailed">
        <div class="event-header">
          <div class="event-date-badge">
            <span class="day">${event.day}</span>
            <span class="month">${event.month}</span>
            <span class="year">${event.year}</span>
          </div>
          <div class="event-title-section">
            <h3>${this.escapeHtml(event.title)}</h3>
          </div>
        </div>
        <div class="event-body">
          <div class="event-details-grid">
            <div class="detail-item">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="10"></circle>
                <polyline points="12 6 12 12 16 14"></polyline>
              </svg>
              <span>${this.escapeHtml(event.time)}</span>
            </div>
            <div class="detail-item">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
                <circle cx="12" cy="10" r="3"></circle>
              </svg>
              <span>${this.escapeHtml(event.location)}</span>
            </div>
          </div>
          <p>${this.escapeHtml(event.description)}</p>
          ${highlightsHtml}
          ${registerButton}
        </div>
      </div>
    `;
  }

  /**
   * Render videos to the page
   */
  renderVideos(container, videos, limit = null) {
    if (!container) return;

    const videosToShow = limit ? videos.slice(0, limit) : videos;

    if (videosToShow.length === 0) {
      container.innerHTML = '<p style="text-align: center; color: var(--text-light);">No videos available at this time.</p>';
      return;
    }

    container.innerHTML = videosToShow.map(video => this.createVideoCard(video)).join('');
  }

  /**
   * Create a video card
   */
  createVideoCard(video) {
    const thumbnailUrl = video.youtubeId
      ? `https://img.youtube.com/vi/${video.youtubeId}/maxresdefault.jpg`
      : null;

    const thumbnailHtml = thumbnailUrl
      ? `<img src="${thumbnailUrl}" alt="${this.escapeHtml(video.title)}" style="width: 100%; height: 100%; object-fit: cover;">`
      : `
        <div class="placeholder-video">
          <svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <polygon points="5 3 19 12 5 21 5 3"></polygon>
          </svg>
        </div>
      `;

    const categoryBadge = video.category
      ? `<span class="video-category">${this.escapeHtml(video.category)}</span>`
      : '';

    const durationMeta = video.duration
      ? `<div class="video-meta"><span>${this.escapeHtml(video.duration)}</span></div>`
      : '';

    const videoLink = video.youtubeUrl || '#';
    const linkTarget = video.youtubeUrl ? 'target="_blank" rel="noopener"' : '';

    return `
      <a href="${this.escapeHtml(videoLink)}" ${linkTarget} class="video-card" data-category="${video.category}">
        <div class="video-thumbnail">
          ${thumbnailHtml}
        </div>
        <div class="video-info">
          ${categoryBadge}
          <h3>${this.escapeHtml(video.title)}</h3>
          <p>${this.escapeHtml(video.description)}</p>
          ${durationMeta}
        </div>
      </a>
    `;
  }

  /**
   * Escape HTML to prevent XSS
   */
  escapeHtml(text) {
    if (!text) return '';
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }
}

// Create global instance
window.dataLoader = new DataLoader();
